### ISSUE TITLE
'Unable to cast object of type 'System.DirectoryServices.AccountManagement.GroupPrincipal' 

### ISSUE THREAD

**Issue by MelbourneDeveloper** [JamesIrish/KeepKeySharp#1]
Run the sample, get:

![image](https://user-images.githubusercontent.com/16697547/43877834-504f9420-9bdf-11e8-8bad-30b993686eae.png)

**Comment by JamesIrish** [comment]
This could well be because of your domain setup.  See this StackOverflow article: https://stackoverflow.com/questions/11014406/unable-to-cast-object-of-type-in-system-directoryservices-accountmanagement-grou
