### ISSUE TITLE
Initialization Doesn't Work

### ISSUE THREAD

**Issue by MelbourneDeveloper** [JamesIrish/KeepKeySharp#2]
I put a breakpoint here and hit F10:

![image](https://user-images.githubusercontent.com/16697547/43878124-da2225ea-9be0-11e8-93c0-fc0605cba689.png)

The debugger doesn't move to the next line. The KKOnConnected event does fire, but the rest of the code does not continue:

![image](https://user-images.githubusercontent.com/16697547/43878162-0cbb1dea-9be1-11e8-93b7-675b18ad5ab2.png)

**Comment by JamesIrish** [comment]
You'll need to step into the KeepKeyDevice or KeepKeyCommunicator class to see what it is responding with.  I haven't updated the definitions in a considerable amount of time.
