### ISSUE TITLE
Coin Logic Injection

### ISSUE THREAD

**Issue by MelbourneDeveloper** [JamesIrish/KeepKeySharp#4]
NBitcoin is a fantastic library which is written by a fantastic programmer. That said, NBitcoin is only good for bitcoin clones, and it is loaded with subdependencies. Any logic that NBitcoin provides should be abstracted out and passed in through dependency injection or not at all. App developers don't want unnecessary bloat. If the developer is developing for Ethereum, the NBitcoin dependency adds bloat for no reason.

**Comment by JamesIrish** [comment]
Thanks for your suggestion but this library is not being maintained.  Feel free to fork it and take it to the next level!
